In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [55]:
fertilizer_recommendations = {
    'arecanut': ['Urea', 'SSP', 'MOP', 'Boron', 'Zinc'],
    'bajra': ['Urea', 'DAP', 'MOP'],
    'banana': ['Urea', 'DAP', 'MOP', 'Magnesium Sulphate', 'Zinc Sulphate', 'Borax'],
    'barley': ['Urea', 'DAP', 'MOP'],
    'blackgram': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'chickpea': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'coconut': ['Urea', 'Rock Phosphate', 'MOP', 'Boron', 'Zinc', 'Iron chelates'],
    'cotton': ['Urea', 'DAP', 'MOP'],
    'dry Chillies': ['Urea', 'DAP', 'MOP', 'Zinc Sulphate', 'Borax'],
    'garlic': ['Urea', 'DAP', 'MOP'],
    'jowar': ['Urea', 'DAP', 'MOP'],
    'jute': ['Urea', 'DAP', 'MOP'],
    'lentil': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'maize': ['Urea', 'DAP', 'MOP'],
    'mothbeans': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'mungbean': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'pigeonpeas': ['Urea (minimal)', 'DAP', 'MOP', 'Rhizobium inoculation'],
    'potato': ['Urea', 'DAP', 'MOP'],
    'ragi': ['Urea', 'DAP', 'MOP'],
    'rice': ['Urea', 'DAP', 'MOP'],
    'small Millets': ['Urea', 'DAP', 'MOP'],
    'sugarcane': ['Urea', 'DAP', 'MOP'],
    'turmeric': ['Urea', 'DAP', 'MOP', 'Zinc Sulphate', 'Borax'],
    'wheat': ['Urea', 'DAP', 'MOP']
}

In [56]:
soil_recommendations = {
    'arecanut': 'Laterite or red loam soil, well-drained',
    'bajra': 'Sandy loam, drought-resistant soil',
    'banana': 'Alluvial soil, rich in organic matter',
    'barley': 'Loamy soil, well-drained, slightly alkaline',
    'blackgram': 'Sandy loam, moderate water retention',
    'chickpea': 'Sandy loam, well-drained, neutral pH',
    'coconut': 'Sandy loam or laterite soil, high drainage',
    'cotton': 'Black soil, moisture-retentive, high fertility',
    'dry Chillies': 'Sandy loam, well-drained, slightly acidic',
    'garlic': 'Sandy loam, well-drained, rich in organic matter',
    'jowar': 'Sandy loam, drought-resistant soil',
    'jute': 'Alluvial soil, high water retention',
    'lentil': 'Sandy loam, moderate water retention',
    'maize': 'Sandy loam, well-drained, fertile soil',
    'mothbeans': 'Sandy loam, drought-resistant soil',
    'mungbean': 'Sandy loam, well-drained, neutral pH',
    'pigeonpeas': 'Sandy loam, well-drained, drought-tolerant',
    'potato': 'Sandy loam, well-aerated, slightly acidic',
    'ragi': 'Sandy loam, well-drained, drought-resistant',
    'rice': 'Clayey soil, high water retention',
    'small Millets': 'Sandy loam, drought-resistant soil',
    'sugarcane': 'Loamy soil, deep, well-drained, high organic matter',
    'turmeric': 'Loamy soil, well-drained, rich in organic matter',
    'wheat': 'Loamy soil, well-drained, slightly alkaline'
}

In [57]:
pest_disease_recommendations = {
    'arecanut': {
        'Pest': 'Red Palm Weevil',
        'Disease': 'Yellow Leaf Disease',
        'Prevention': 'Apply insecticides like Chlorpyrifos, remove infected palms'
    },
    'bajra': {
        'Pest': 'Stem Borer',
        'Disease': 'Ergot Disease',
        'Prevention': 'Use resistant varieties, spray Carbendazim fungicide'
    },
    'banana': {
        'Pest': 'Banana Weevil',
        'Disease': 'Panama Wilt',
        'Prevention': 'Plant disease-free suckers, use biocontrol agents like Trichoderma'
    },
    'barley': {
        'Pest': 'Aphids',
        'Disease': 'Powdery Mildew',
        'Prevention': 'Apply sulfur-based fungicides, practice crop rotation'
    },
    'blackgram': {
        'Pest': 'Pod Borer',
        'Disease': 'Yellow Mosaic Virus',
        'Prevention': 'Use resistant varieties, control aphid vectors with Neem oil'
    },
    'chickpea': {
        'Pest': 'Gram Pod Borer',
        'Disease': 'Fusarium Wilt',
        'Prevention': 'Plant resistant varieties, use seed treatment with Thiram'
    },
    'coconut': {
        'Pest': 'Coconut Caterpillar',
        'Disease': 'Root Wilt',
        'Prevention': 'Remove infected leaves, apply Bordeaux mixture'
    },
    'cotton': {
        'Pest': 'Bollworm',
        'Disease': 'Wilt Disease',
        'Prevention': 'Plant resistant varieties, use Neem-based pesticides'
    },
    'dry Chillies': {
        'Pest': 'Thrips',
        'Disease': 'Dieback Disease',
        'Prevention': 'Spray Neem oil, maintain proper drainage'
    },
    'garlic': {
        'Pest': 'Onion Thrips',
        'Disease': 'White Rot',
        'Prevention': 'Crop rotation, apply Fungicides like Hexaconazole'
    },
    'jowar': {
        'Pest': 'Shoot Fly',
        'Disease': 'Grain Mold',
        'Prevention': 'Use resistant varieties, spray Mancozeb fungicide'
    },
    'jute': {
        'Pest': 'Semi Looper',
        'Disease': 'Stem Rot',
        'Prevention': 'Remove infected plants, apply biofungicides'
    },
    'lentil': {
        'Pest': 'Pod Borer',
        'Disease': 'Rust',
        'Prevention': 'Spray wettable sulfur, plant early-maturing varieties'
    },
    'maize': {
        'Pest': 'Stem Borer',
        'Disease': 'Maize Smut',
        'Prevention': 'Use resistant hybrids, remove infected plants'
    },
    'mothbeans': {
        'Pest': 'Pod Borer',
        'Disease': 'Powdery Mildew',
        'Prevention': 'Spray sulfur-based fungicides, practice crop rotation'
    },
    'mungbean': {
        'Pest': 'Yellow Mosaic Virus Vector',
        'Disease': 'Yellow Mosaic Virus',
        'Prevention': 'Use resistant varieties, control aphids with Neem oil'
    },
    'pigeonpeas': {
        'Pest': 'Pod Fly',
        'Disease': 'Fusarium Wilt',
        'Prevention': 'Plant resistant varieties, use Trichoderma-treated seeds'
    },
    'potato': {
        'Pest': 'Potato Tuber Moth',
        'Disease': 'Late Blight',
        'Prevention': 'Use certified seeds, spray copper-based fungicides'
    },
    'ragi': {
        'Pest': 'Shoot Fly',
        'Disease': 'Blast Disease',
        'Prevention': 'Use resistant varieties, apply Carbendazim fungicide'
    },
    'rice': {
        'Pest': 'Brown Plant Hopper',
        'Disease': 'Blast Disease',
        'Prevention': 'Use pheromone traps, spray Neem oil'
    },
    'small Millets': {
        'Pest': 'Shoot Fly',
        'Disease': 'Smut Disease',
        'Prevention': 'Treat seeds with Carboxin, practice crop rotation'
    },
    'sugarcane': {
        'Pest': 'Top Borer',
        'Disease': 'Red Rot',
        'Prevention': 'Plant disease-free setts, apply Bordeaux mixture'
    },
    'turmeric': {
        'Pest': 'Rhizome Scale',
        'Disease': 'Leaf Spot',
        'Prevention': 'Apply Neem cake, spray Mancozeb fungicide'
    },
    'wheat': {
        'Pest': 'Aphids',
        'Disease': 'Rust Disease',
        'Prevention': 'Apply sulfur-based fungicides, practice crop rotation'
    }
}

In [58]:
def importdata():
	balance_data = pd.read_csv("cropRecommend_final.csv")
	
	#print ("Dataset Length: ", len(balance_data))
	#print ("Dataset Shape: ", balance_data.shape)
	
	#print ("Dataset: ",balance_data.head())
	return balance_data

In [59]:
def splitdataset(balance_data):
 	# Separating the target variable
	X = balance_data.values[:, 0:11]
	Y = balance_data.values[:, 11]
	
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test

In [60]:
# Function to perform training with entropy.
def train_using_entropy(X_train, X_test, y_train):
	
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 15, min_samples_leaf = 5)
	
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


In [61]:
def prediction(X_test, clf_object):
	
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	
	return y_pred

In [62]:
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: \n",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred, zero_division=1))

In [63]:
def train_using_gini(X_train, X_test, y_train):
    clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=14, min_samples_leaf=5)
  
    clf_gini.fit(X_train, y_train)
    return clf_gini

In [64]:
# Function to take user input and predict the best crop
def predict_crop_from_user_input(clf_entropy):
    print("\nEnter the following values for prediction:")

    feature_names = ['SO2', 'NO2', 'RSPM', 'SPM', 'N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
    user_input = []

    for feature in feature_names:
        value = float(input(f"Enter {feature}: "))
        user_input.append(value)

    # Convert input to NumPy array and reshape for prediction
    user_input = np.array(user_input).reshape(1, -1)

    # Make prediction
    prediction_result = clf_entropy.predict(user_input)

    predicted_crop = prediction_result[0]

    # Get recommended fertilizers
    recommended_fertilizers = fertilizer_recommendations.get(predicted_crop, ["No specific recommendation available"])
    soil_type = soil_recommendations.get(predicted_crop, "No specific soil information available")
    pest_disease = pest_disease_recommendations.get(predicted_crop, {})


    print(f"\nPredicted Crop: {predicted_crop}")
    print(f"Recommended Fertilizers: {', '.join(recommended_fertilizers)}")
    print(f"🧑‍🌾 **Best Soil Type:** {soil_type}")
    print(f"🐞 **Common Pest:** {pest_disease.get('Pest', 'No pest info available')} | 🌿 **Disease:** {pest_disease.get('Disease', 'No disease info available')}")
    print(f"🛡 **Prevention Methods:** {pest_disease.get('Prevention', 'No prevention methods available')}")

In [65]:
def main():
    # Building Phase
    data = importdata()
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
    
    
    clf_entropy = train_using_entropy(X_train, X_test, y_train)
    
    clf_gini = train_using_gini(X_train, X_test, y_train)
    
    
    print("Results Using Entropy:")
    # Prediction using entropy
    y_pred_entropy = prediction(X_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)

    predict_crop_from_user_input(clf_entropy)
    
    print("Results Using Gini")
    # Prediction using gini
    y_pred_gini = prediction(X_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)

In [66]:
if __name__=="__main__":
	main()

Results Using Entropy:
Predicted values:
Confusion Matrix: 
 [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0 37  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  

Enter SO2:  9
Enter NO2:  20
Enter RSPM:  85
Enter SPM:  180
Enter N:  90
Enter P:  50
Enter K:  50
Enter temperature:  20
Enter humidity:  80
Enter ph:  6
Enter rainfall:  350



Predicted Crop: rice
Recommended Fertilizers: Urea, DAP, MOP
🧑‍🌾 **Best Soil Type:** Clayey soil, high water retention
🐞 **Common Pest:** Brown Plant Hopper | 🌿 **Disease:** Blast Disease
🛡 **Prevention Methods:** Use pheromone traps, spray Neem oil
Results Using Gini
Predicted values:
Confusion Matrix: 
 [[ 0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 35  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0 33  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0 37  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 